from typing import Any, Optional, Sequence, Union

class Image:
    format: str
    width: int
    height: int
    bands: int
    dtype: str
    filename: str

    @classmethod
    def new_from_file(
        cls, vips_filename: str, access: Optional[str] = None, **kwargs: Any
    ) -> "Image": ...
    @classmethod
    def new_from_buffer(
        cls, data: Union[bytes, bytearray], options: str = "", **kwargs: Any
    ) -> "Image": ...
    @classmethod
    def thumbnail(
        cls, filename: str, width: int, height: Optional[int] = None, **kwargs: Any
    ) -> "Image": ...
    def thumbnail_image(
        self, width: int, height: Optional[int] = None, **kwargs: Any
    ) -> "Image": ...
    def resize(self, scale: float, **kwargs: Any) -> "Image": ...
    def write_to_file(self, filename: str, **kwargs: Any) -> None: ...
    def write_to_buffer(self, suffix: str, **kwargs: Any) -> bytes: ...
    def crop(self, left: int, top: int, width: int, height: int) -> "Image": ...
    def bandjoin(self, other: Union["Image", Sequence["Image"]]) -> "Image": ...
    def gravity(self, direction: str, width: int, height: int) -> "Image": ...
    def embed(
        self, x: int, y: int, width: int, height: int, extend: Optional[int] = None
    ) -> "Image": ...
    def flatten(self, **kwargs: Any) -> "Image": ...
    def copy_memory(self) -> "Image": ...
    def colourspace(self, space: str) -> "Image": ...
    def autorot(self) -> "Image": ...
    def cast(self, format: str) -> "Image": ...
    def contains(self, x: int, y: int) -> bool: ...
    def get(self, name: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...
    def write_to_memory(self) -> bytes: ...

# Add more as needed from pyvips.Operation or pyvips.Interpretation
