from typing import Any, Dict, Generic, List, Protocol, TypeVar

T = TypeVar("T")


class APIResponse(Generic[T]):
    def __init__(self, data: T, error: Any = None):
        self.data = data
        self.error = error


class AsyncQueryRequestBuilder(Protocol, Generic[T]):
    def insert(self, json: Dict[str, Any]) -> "AsyncQueryRequestBuilder[T]": ...
    def update(self, json: Dict[str, Any]) -> "AsyncQueryRequestBuilder[T]": ...
    def select(self, *columns: str) -> "AsyncQueryRequestBuilder[T]": ...
    def eq(self, column: str, value: Any) -> "AsyncQueryRequestBuilder[T]": ...
    def order(
        self, column: str, desc: bool = False
    ) -> "AsyncQueryRequestBuilder[T]": ...
    def single(self) -> "AsyncQueryRequestBuilder[T]": ...
    async def execute(self) -> APIResponse[T]: ...


class AsyncSupabaseTable(Protocol, Generic[T]):
    def insert(self, json: Dict[str, Any]) -> AsyncQueryRequestBuilder[T]: ...
    def update(self, json: Dict[str, Any]) -> AsyncQueryRequestBuilder[T]: ...
    def select(self, *columns: str) -> AsyncQueryRequestBuilder[List[T]]: ...
    def eq(self, column: str, value: Any) -> AsyncQueryRequestBuilder[List[T]]: ...
    def single(self) -> AsyncQueryRequestBuilder[T]: ...
    def order(
        self, column: str, desc: bool = False
    ) -> AsyncQueryRequestBuilder[List[T]]: ...


class AsyncSupabaseClient(Protocol):
    def table(self, name: str) -> AsyncSupabaseTable[Any]: ...
